"""
Utility functions for processing BrainFlow CSV files.

This module provides common utilities for loading and processing CSV files
generated by BrainFlow, eliminating duplicate code across the codebase.
"""

import pandas as pd
import numpy as np


def load_brainflow_csv_raw(csv_path: str) -> np.ndarray:
    """Load BrainFlow CSV file and return raw transposed data.
    
    Args:
        csv_path: Path to BrainFlow CSV file (tab-separated, no headers)
        
    Returns:
        np.ndarray: Transposed data in (channels, samples) format
        
    Note:
        BrainFlow CSV format uses tab separation with no headers.
        Data is transposed from (samples, channels) to (channels, samples)
        for compatibility with BrainFlow processing expectations.
    """
    csv_data = pd.read_csv(csv_path, sep='\t', header=None, dtype=float)
    return csv_data.values.T  # (channels, samples)