name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Check available Qt6 packages
        run: |
          sudo apt-get update
          echo "=== Available Qt6 packages ==="
          apt-cache search qt6 | grep -i "qt6" | sort
          echo -e "\n=== Package versions ==="
          apt-cache policy qt6-base-dev qt6-declarative-dev
          echo -e "\n=== Package details ==="
          apt-cache show qt6-base-dev qt6-declarative-dev

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo add-apt-repository universe -y
          sudo apt-get update
          sudo apt-get install -y -V \
            qt6-base-dev \
            qt6-declarative-dev \
            qt6-tools-dev \
            qt6-tools-dev-tools \
            libqt6gui6 \
            libqt6widgets6 \
            libqt6core6 \
            libqt6opengl6 \
            libhdf5-dev \
            libopenblas-dev \
            liblapack-dev \
            libffi-dev \
            libssl-dev \
            xvfb

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          CI: true
          QT_QPA_PLATFORM: offscreen
          QT_LOGGING_RULES: "*.debug=false;qt.qpa.*=false;qt.widgets.*=false"
          QT_DEBUG_PLUGINS: 0
          DISPLAY: :99
          PYTHONUNBUFFERED: 1
        run: |
          Xvfb :99 -screen 0 1920x1080x24 -ac &
          sleep 3
          pytest -v gssc_local/tests/ -k "not pyqt" --ignore=gssc_local/tests/test_pyqt_visualizer.py --ignore=gssc_local/tests/test_pyqt_visualizer_real_data.py --ignore=gssc_local/tests/test_visualizer_real_data.py --ignore=gssc_local/tests/test_processor_improved.py --ignore=gssc_local/tests/test_visualizer_synthetic_data.py --ignore=gssc_local/tests/test_implementation_plans.py --ignore=gssc_local/tests/test_gap_handler.py --ignore=gssc_local/tests/test_csv_manager.py --ignore=gssc_local/tests/test_speed_controlled_board_manager.py
