name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qt6-base-dev \
            qt6-declarative-dev \
            qt6-gui-dev \
            qt6-widgets-dev \
            qt6-opengl-dev \
            libqt6gui6 \
            libqt6widgets6 \
            libqt6core6 \
            libqt6opengl6 \
            libhdf5-dev \
            libopenblas-dev \
            liblapack-dev \
            libffi-dev \
            libssl-dev \
            xvfb

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Run tests
        env:
          CI: true
          QT_QPA_PLATFORM: offscreen
          QT_LOGGING_RULES: "*.debug=false;qt.qpa.*=false"
          QT_DEBUG_PLUGINS: 0
          DISPLAY: :99
          PYTHONUNBUFFERED: 1
        run: |
          # Start Xvfb with a larger screen size and more color depth
          Xvfb :99 -screen 0 1920x1080x24 -ac &
          sleep 3  # Give Xvfb time to start

          # Run tests with increased verbosity
          pytest -v gssc_local/tests/
