name: Python Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qt6-base-dev \
            qt6-declarative-dev \
            libqt6gui6 \
            libqt6widgets6 \
            libqt6core6 \
            libqt6opengl6 \
            libhdf5-dev \
            libopenblas-dev \
            liblapack-dev \
            libffi-dev \
            libssl-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -r requirements.txt

      - name: Run tests
        env:
          CI: true
        run: |
          pytest gssc_local/tests/
